import json
import os
import subprocess
import sys
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

from tests.runtime_test_support import ROOT


class RuntimeDeepSeekProviderExampleTestsMixin:
    def test_deepseek_fallback_provider_uses_chat_completion_contract(self) -> None:
        response_content = {
            "code": "def run(tools, **kwargs):\n    return {'status': 'completed'}\n",
            "provider_name": "deepseek_fallback_provider",
            "reason": "Generated by fake DeepSeek server.",
        }
        with _fake_deepseek_server(response_content) as server:
            result = _run_provider_script(
                ROOT / "examples" / "providers" / "deepseek_fallback_provider.py",
                {
                    "skill_name": "deepseek_contract_test",
                    "summary": "Generate a simple skill.",
                    "docstring": "A simple skill.",
                    "input_schema": {},
                    "trajectory": {},
                    "prompt": "Generate a simple skill.",
                },
                server.url,
            )

        self.assertEqual(0, result.returncode, result.stderr)
        payload = json.loads(result.stdout)
        self.assertEqual("deepseek_fallback_provider", payload["provider_name"])
        self.assertIn("def run", payload["code"])
        self.assertEqual("/chat/completions", server.received_path)
        self.assertEqual("Bearer test-deepseek-key", server.received_headers["Authorization"])
        self.assertEqual("deepseek-v4-flash", server.received_body["model"])
        self.assertEqual({"type": "json_object"}, server.received_body["response_format"])

    def test_deepseek_semantic_provider_uses_chat_completion_contract(self) -> None:
        response_content = {
            "provider_name": "deepseek_semantic_review_provider",
            "summary": "No blocking issue.",
            "issues": [],
        }
        with _fake_deepseek_server(response_content) as server:
            result = _run_provider_script(
                ROOT / "examples" / "providers" / "deepseek_semantic_review_provider.py",
                {
                    "file_path": "skill_store/staging/example.py",
                    "source": "def run(tools, **kwargs):\n    return {'status': 'completed'}",
                    "trajectory": None,
                    "heuristic_issues": [],
                    "prompt": "Review candidate.",
                },
                server.url,
            )

        self.assertEqual(0, result.returncode, result.stderr)
        payload = json.loads(result.stdout)
        self.assertEqual("deepseek_semantic_review_provider", payload["provider_name"])
        self.assertEqual([], payload["issues"])
        self.assertEqual("/chat/completions", server.received_path)
        self.assertEqual("Bearer test-deepseek-key", server.received_headers["Authorization"])
        self.assertEqual("deepseek-v4-flash", server.received_body["model"])
        self.assertEqual({"type": "json_object"}, server.received_body["response_format"])


class _FakeDeepSeekServer:
    def __init__(self, response_content: dict) -> None:
        self.response_content = response_content
        self.received_path: str | None = None
        self.received_headers: dict[str, str] = {}
        self.received_body: dict = {}
        self._server: HTTPServer | None = None
        self._thread: threading.Thread | None = None
        self.url = ""

    def __enter__(self):
        owner = self

        class Handler(BaseHTTPRequestHandler):
            def do_POST(self) -> None:
                content_length = int(self.headers.get("Content-Length", "0"))
                body = self.rfile.read(content_length).decode("utf-8")
                owner.received_path = self.path
                owner.received_headers = dict(self.headers.items())
                owner.received_body = json.loads(body)
                response = {
                    "choices": [
                        {
                            "message": {
                                "content": json.dumps(owner.response_content),
                            }
                        }
                    ]
                }
                encoded = json.dumps(response).encode("utf-8")
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(encoded)))
                self.end_headers()
                self.wfile.write(encoded)

            def log_message(self, format: str, *args) -> None:
                return

        self._server = HTTPServer(("127.0.0.1", 0), Handler)
        host, port = self._server.server_address
        self.url = f"http://{host}:{port}"
        self._thread = threading.Thread(target=self._server.serve_forever, daemon=True)
        self._thread.start()
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        if self._server:
            self._server.shutdown()
            self._server.server_close()
        if self._thread:
            self._thread.join(timeout=5)


def _fake_deepseek_server(response_content: dict) -> _FakeDeepSeekServer:
    return _FakeDeepSeekServer(response_content)


def _run_provider_script(script_path: Path, request: dict, base_url: str) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env.update(
        {
            "DEEPSEEK_API_KEY": "test-deepseek-key",
            "DEEPSEEK_API_BASE": base_url,
            "DEEPSEEK_MODEL": "deepseek-v4-flash",
            "PYTHONIOENCODING": "utf-8",
        }
    )
    return subprocess.run(
        [sys.executable, str(script_path)],
        input=json.dumps(request, ensure_ascii=False),
        capture_output=True,
        text=True,
        encoding="utf-8",
        env=env,
        check=False,
        timeout=30,
    )
